// ========================================
// DATA MODEL - Route Stops and Sub-routes
// ========================================

/**
 * IMPORTANT: 
 * - Điểm nhận (start) và Điểm giao (end) là BẮT BUỘC
 * - Điểm quay về (return) TỰ ĐỘNG thêm - luôn quay về điểm bắt đầu
 * - Điểm dừng (waypoint) là OPTIONAL - user có thể thêm sau
 */

let routeData = {
    // 5 điểm: Bắt đầu + 2 Điểm dừng + Đích đến + Quay về
    stops: [
        {
            id: 'stop-start',
            label: 'Điểm bắt đầu',
            address: 'Sân bay Tân Sơn Nhất',
            fullAddress: 'Sân bay Tân Sơn Nhất, Tân Bình, TP.HCM',
            type: 'start',
            required: true,
            editable: true
        },
        {
            id: 'stop-1',
            label: 'ĐIỂM DỪNG 1',
            address: 'Chợ Bến Thành',
            fullAddress: 'Chợ Bến Thành, Đ. Lê Lợi, Bến Thành, Quận 1, TP.HCM',
            type: 'waypoint',
            required: false,
            editable: true
        },
        {
            id: 'stop-2',
            label: 'ĐIỂM DỪNG 2',
            address: 'Landmark 81',
            fullAddress: 'Landmark 81, 720A Đ. Điện Biên Phủ, Bình Thạnh, TP.HCM',
            type: 'waypoint',
            required: false,
            editable: true
        },
        {
            id: 'stop-end',
            label: 'Đích đến',
            address: 'Thảo Cầm Viên',
            fullAddress: 'Thảo Cầm Viên Sài Gòn, 2 Nguyễn Bỉnh Khiêm, Quận 1, TP.HCM',
            type: 'end',
            required: true,
            editable: true
        },
        {
            id: 'stop-return',
            label: 'QUAY VỀ',
            address: '',
            fullAddress: 'Quay về điểm bắt đầu',
            type: 'return',
            required: true,
            editable: false,
            autoGenerated: true
        }
    ],

    // 4 sub-routes nối các điểm
    subRoutes: [
        {
            id: 'subroute-1',
            fromStopId: 'stop-start',
            toStopId: 'stop-1',
            estimatedDistance: 7.5,
            actualDistance: 7.5,
            estimatedTime: 25
        },
        {
            id: 'subroute-2',
            fromStopId: 'stop-1',
            toStopId: 'stop-2',
            estimatedDistance: 4.2,
            actualDistance: 4.2,
            estimatedTime: 15
        },
        {
            id: 'subroute-3',
            fromStopId: 'stop-2',
            toStopId: 'stop-end',
            estimatedDistance: 2.8,
            actualDistance: 2.8,
            estimatedTime: 10
        },
        {
            id: 'subroute-4',
            fromStopId: 'stop-end',
            toStopId: 'stop-return',
            estimatedDistance: 6.5,
            actualDistance: 6.5,
            estimatedTime: 20
        }
    ]
};

// ========================================
// UTILITY FUNCTIONS
// ========================================

/**
 * Tính tổng khoảng cách từ sub-routes
 */
function calculateTotalDistance(subRoutes, field = 'actualDistance') {
    return subRoutes.reduce((total, route) => total + route[field], 0);
}

/**
 * Tính chênh lệch giữa khoảng cách thực tế và ước lượng
 */
function calculateDifference(actual, estimated) {
    const diff = actual - estimated;

    // Tránh chia cho 0
    let percentage;
    if (estimated === 0) {
        percentage = actual === 0 ? '0.0' : '100.0';
    } else {
        percentage = ((diff / estimated) * 100).toFixed(1);
    }

    const sign = diff >= 0 ? '+' : '';
    return {
        value: diff,
        text: `${sign}${diff} km (${sign}${percentage}%)`
    };
}

/**
 * Lấy marker type dựa vào stop type
 */
function getMarkerClass(type) {
    const classMap = {
        'start': 'start',
        'end': 'end',
        'return': 'return',
        'waypoint': ''
    };
    return classMap[type] || '';
}

/**
 * Tạo ID mới cho stop
 */
function generateStopId() {
    return 'stop-' + Date.now();
}

/**
 * Tạo ID mới cho sub-route
 */
function generateSubRouteId() {
    return 'subroute-' + Date.now();
}

// ========================================
// RENDER FUNCTIONS
// ========================================

/**
 * Render toàn bộ timeline với stops và sub-routes
 */
function renderTimeline() {
    const timeline = document.getElementById('routeTimeline');
    if (!timeline) return;

    timeline.innerHTML = '';

    // Render từng stop và sub-route sau nó
    routeData.stops.forEach((stop, index) => {
        const timelineItem = createTimelineItem(stop, index);
        timeline.appendChild(timelineItem);
    });

    // Update summary counts
    updateSummary();

    // Update stats
    updateStats();
}

/**
 * Tạo 1 timeline item (bao gồm stop row + sub-route nếu có)
 */
function createTimelineItem(stop, index) {
    const item = document.createElement('div');
    item.className = 'timeline-item';
    item.dataset.stopId = stop.id;

    // Create stop row
    const stopRow = createStopRow(stop, index);
    item.appendChild(stopRow);

    // Create sub-route (nếu không phải stop cuối cùng)
    if (index < routeData.stops.length - 1) {
        const nextStop = routeData.stops[index + 1];
        const subRoute = routeData.subRoutes.find(
            sr => sr.fromStopId === stop.id && sr.toStopId === nextStop.id
        );

        if (subRoute) {
            const subRouteElement = createSubRoute(subRoute, stop, nextStop);
            item.appendChild(subRouteElement);
        }
    }

    return item;
}

/**
 * Tạo stop row (draggable)
 */
function createStopRow(stop, index) {
    const row = document.createElement('div');
    row.className = 'stop-row';
    row.dataset.stopId = stop.id;

    // Marker content: Số cho stops thường, Icon cho return
    let markerContent;
    if (stop.type === 'return') {
        // Icon quay về (return arrow)
        markerContent = `
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" style="width: 20px; height: 20px;">
                <polyline points="1 4 1 10 7 10"></polyline>
                <path d="M3.51 15a9 9 0 1 0 2.13-9.36L1 10"></path>
            </svg>
        `;
    } else {
        // Số thứ tự
        markerContent = index + 1;
    }

    // Note cho return stop
    let addressClass = 'stop-address';
    if (stop.type === 'return') {
        addressClass += ' return-note';
    } else if (stop.address) {
        // Nếu có địa chỉ (đã nhập) -> màu đen
        addressClass += ' filled';
    }

    const addressDisplay = `<div class="${addressClass}">${stop.fullAddress}</div>`;

    row.innerHTML = `
        <!-- Drag Handle -->
        <div class="drag-handle" style="${stop.type === 'return' ? 'cursor: default;' : ''}">
            ${stop.type !== 'return' ? `
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <line x1="9" y1="5" x2="9" y2="19"></line>
                <line x1="15" y1="5" x2="15" y2="19"></line>
            </svg>
            ` : ''}
        </div>
        
        <!-- Stop Marker -->
        <div class="stop-marker">
            ${markerContent}
        </div>
        
        <!-- Stop Info -->
        <div class="stop-info">
            <div class="stop-label">${stop.label}</div>
            ${addressDisplay}
        </div>
        
        <!-- Stop Actions -->
        <div class="stop-actions">
            ${stop.editable !== false ? `
            <button class="stop-action-btn edit" onclick="editStop('${stop.id}')">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>
                    <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>
                </svg>
            </button>
            ` : ''}
            ${!stop.required ? `
            <button class="stop-action-btn delete" onclick="deleteStop('${stop.id}')" title="Xóa điểm dừng">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <line x1="18" y1="6" x2="6" y2="18"></line>
                    <line x1="6" y1="6" x2="18" y2="18"></line>
                </svg>
            </button>
            ` : ''}
        </div>
    `;

    return row;
}

/**
 * Tạo sub-route element giữa 2 stops
 */
function createSubRoute(subRoute, fromStop, toStop) {
    const div = document.createElement('div');
    div.className = 'sub-route';
    div.dataset.subrouteId = subRoute.id;

    div.innerHTML = `
        <!-- Sub-route Content -->
        <div class="sub-route-content">
            <div class="sub-route-label">TUYẾN CON ${subRoute.id.replace('subroute-', '')}</div>
            
            <div class="sub-route-info">
                <!-- Distance Info -->
                <div class="sub-route-distance">
                    <div class="distance-item estimated">
                        <span>Ước lượng:</span>
                        <span class="distance-value">${subRoute.estimatedDistance} km</span>
                    </div>
                    
                    <span style="color: #ddd;">|</span>
                    
                    <div class="distance-item actual">
                        <span>Thực tế:</span>
                        <input 
                            type="number" 
                            class="distance-input" 
                            value="${subRoute.actualDistance}"
                            min="0"
                            step="0.1"
                            data-subroute-id="${subRoute.id}"
                            onchange="updateActualDistance('${subRoute.id}', this.value)"
                        />
                        <span>km</span>
                    </div>
                </div>
            </div>
        </div>
    `;

    return div;
}

/**
 * Update summary (số điểm dừng, số tuyến con)
 * Note: "Quay về" KHÔNG tính vào số điểm
 */
function updateSummary() {
    const stopsCount = document.getElementById('stopsCount');
    const subRoutesCount = document.getElementById('subRoutesCount');

    if (stopsCount) {
        // Chỉ đếm stops thật (không tính return)
        const actualStops = routeData.stops.filter(s => s.type !== 'return');
        stopsCount.textContent = `${actualStops.length} điểm`;
    }

    if (subRoutesCount) {
        subRoutesCount.textContent = `${routeData.subRoutes.length} tuyến con`;
    }
}

/**
 * Update stats (tổng ước lượng, tổng thực tế, chênh lệch)
 */
function updateStats() {
    const totalEstimated = calculateTotalDistance(routeData.subRoutes, 'estimatedDistance');
    const totalActual = calculateTotalDistance(routeData.subRoutes, 'actualDistance');
    const difference = calculateDifference(totalActual, totalEstimated);

    const estimatedEl = document.getElementById('totalEstimated');
    const actualEl = document.getElementById('totalActual');
    const differenceEl = document.getElementById('totalDifference');

    if (estimatedEl) {
        estimatedEl.textContent = `${totalEstimated} km`;
    }

    if (actualEl) {
        actualEl.textContent = `${totalActual} km`;
    }

    if (differenceEl) {
        differenceEl.textContent = difference.text;
        // Update class based on positive/negative
        differenceEl.classList.toggle('positive', difference.value < 0);
    }
}

// ========================================
// EVENT HANDLERS
// ========================================

/**
 * Update actual distance khi user thay đổi
 */
function updateActualDistance(subRouteId, newValue) {
    const subRoute = routeData.subRoutes.find(sr => sr.id === subRouteId);
    if (subRoute) {
        subRoute.actualDistance = parseFloat(newValue) || 0;
        updateStats();
        console.log(`✅ Updated ${subRouteId} actual distance to ${newValue} km`);
    }
}

/**
 * Edit stop (placeholder - bạn có thể implement modal sau)
 */
function editStop(stopId) {
    const stop = routeData.stops.find(s => s.id === stopId);
    if (stop) {
        alert(`Edit stop: ${stop.fullAddress}\n(Feature coming soon...)`);
        console.log('Edit stop:', stop);
    }
}

/**
 * Delete stop và rebuild sub-routes
 */
function deleteStop(stopId) {
    const stopIndex = routeData.stops.findIndex(s => s.id === stopId);
    if (stopIndex === -1) return;

    const stop = routeData.stops[stopIndex];

    if (!confirm(`Xóa điểm dừng: ${stop.fullAddress}?`)) {
        return;
    }

    // Remove stop
    routeData.stops.splice(stopIndex, 1);

    // Rebuild sub-routes
    rebuildSubRoutes();

    // Re-render
    renderTimeline();

    console.log(`🗑️ Deleted stop: ${stopId}`);
}

/**
 * Add new stop (placeholder)
 */
function addStop() {
    alert('Thêm điểm dừng mới\n(Feature coming soon...)');

    // Example implementation:
    // const newStop = {
    //     id: generateStopId(),
    //     label: 'ĐIỂM DỪNG',
    //     address: 'Địa chỉ mới',
    //     fullAddress: 'Địa chỉ đầy đủ',
    //     type: 'waypoint'
    // };
    // routeData.stops.push(newStop);
    // rebuildSubRoutes();
    // renderTimeline();
}

/**
 * Rebuild sub-routes sau khi thay đổi thứ tự hoặc xóa/thêm stops
 */
function rebuildSubRoutes() {
    const newSubRoutes = [];

    for (let i = 0; i < routeData.stops.length - 1; i++) {
        const fromStop = routeData.stops[i];
        const toStop = routeData.stops[i + 1];

        // Tìm sub-route cũ (nếu có) để giữ lại actual distance
        const existingSubRoute = routeData.subRoutes.find(
            sr => sr.fromStopId === fromStop.id && sr.toStopId === toStop.id
        );

        if (existingSubRoute) {
            // Giữ lại sub-route cũ
            newSubRoutes.push(existingSubRoute);
        } else {
            // Tạo sub-route mới với ước lượng mặc định
            newSubRoutes.push({
                id: generateSubRouteId(),
                fromStopId: fromStop.id,
                toStopId: toStop.id,
                estimatedDistance: 10, // Default - có thể call Google Maps API sau
                actualDistance: 10,
                estimatedTime: 15
            });
        }
    }

    routeData.subRoutes = newSubRoutes;
    console.log('🔄 Rebuilt sub-routes:', newSubRoutes.length);
}

// ========================================
// DRAG & DROP with SortableJS
// ========================================

let sortableInstance = null;

/**
 * Initialize drag & drop cho timeline
 */
function initDragAndDrop() {
    const timeline = document.getElementById('routeTimeline');
    if (!timeline) return;

    // Destroy existing instance if any
    if (sortableInstance) {
        sortableInstance.destroy();
    }

    // Create new Sortable instance
    sortableInstance = Sortable.create(timeline, {
        animation: 200,           // Animation duration (ms)
        easing: "cubic-bezier(1, 0, 0, 1)",
        handle: '.drag-handle',   // Drag handle selector
        draggable: '.timeline-item', // Draggable items
        ghostClass: 'sortable-ghost',
        chosenClass: 'sortable-chosen',
        dragClass: 'sortable-drag',

        // Event khi bắt đầu drag
        onStart: function (evt) {
            console.log('🖐️ Start dragging item:', evt.oldIndex);
        },

        // Event khi kết thúc drag (thả)
        onEnd: function (evt) {
            const oldIndex = evt.oldIndex;
            const newIndex = evt.newIndex;

            console.log(`📍 Moved from index ${oldIndex} to ${newIndex}`);

            // Update data model
            const movedStop = routeData.stops.splice(oldIndex, 1)[0];
            routeData.stops.splice(newIndex, 0, movedStop);

            // Rebuild sub-routes với thứ tự mới
            rebuildSubRoutes();

            // Re-render timeline
            renderTimeline();

            // Re-init drag & drop
            initDragAndDrop();
        }
    });

    console.log('✅ Drag & Drop initialized');
}

// ========================================
// MAP COLLAPSIBLE
// ========================================

/**
 * Toggle map section (collapse/expand)
 */
function initMapToggle() {
    const mapToggle = document.getElementById('mapToggle');
    const mapContent = document.getElementById('mapContent');

    if (!mapToggle || !mapContent) return;

    mapToggle.addEventListener('click', function () {
        mapToggle.classList.toggle('collapsed');
        mapContent.classList.toggle('collapsed');
    });
}

// ========================================
// INITIALIZATION
// ========================================

/**
 * Initialize app khi DOM loaded
 */
document.addEventListener('DOMContentLoaded', function () {
    console.log('🚀 Route Management App Initialized');

    // Render timeline
    renderTimeline();

    // Initialize drag & drop
    initDragAndDrop();

    // Initialize map toggle
    initMapToggle();

    // Add Stop button handler
    const btnCreateStop = document.getElementById('btnCreateStop');
    if (btnCreateStop) {
        btnCreateStop.addEventListener('click', addStop);
    }

    console.log('📊 Route Data:', routeData);
    console.log('✨ App ready!');
});
